### ISSUE TITLE
poor preprocessing effect

### ISSUE THREAD

**Issue by QQuince** [Rohit-Kundu/MFSNet#1]
Hi!
I'm having some problems with image preprocessing.The original configuration code provided does not have a good effect after preprocessing. Is there something wrong with me? Looking forward to your reply!
Thank you very much!

Best,
Quince.

![0000043](https://user-images.githubusercontent.com/104144036/164461543-d4af9497-0013-4f4e-9264-b133a5905a1d.jpg)

(original)

![0000043](https://user-images.githubusercontent.com/104144036/164461604-bd2e561e-21cf-4e1e-b4bc-3480ffa792e6.png)

(after preprocessing)

**Comment by hritam-98** [comment]
I guess you should look into the theory behind inpainting [here](https://pyimagesearch.com/2020/05/18/image-inpainting-with-opencv-and-python/) 

You should change some parameters and check which one works best for your image. We have shown two test cases for our images and also tried to find some parameters for your image. However, this is not optimal. You are free to try it on your own. 

[Colab Notebook](https://colab.research.google.com/drive/16YGyc0Q_PD27MU6_uJ1no33QoC05f48i?usp=sharing)

**Comment by QQuince** [comment]
Thank you for your reply. I read the link you recommended to me carefully. After understanding the principle of Inpaint, I modified the code parameters according to the image and got a good preprocessing effect. Can you share the ISIC2017 dataset inpaint preprocessing parameters for my reference?I would be very grateful if you could.

Best,
Quince.
